/**
 * 테스트 시스템 초기화 모듈
 * Test System Initialization Module
 *
 * 테스트 시스템을 초기화하는 기능을 제공합니다.
 * Provides functionality to initialize the test system.
 *
 * Generated by Copilot
 */

import { TestRunner } from './runner.js';
import { TestReporter } from './reporter.js';

// 파일 시스템 테스트 케이스
import { fileSystemTests } from './cases/fileSystem/index.js';

// 터미널 테스트 케이스
import { terminalTests } from './cases/terminal/index.js';

// 컨텍스트 테스트 케이스
import { contextTests } from './cases/context/index.js';

// 번역 테스트 케이스
import { translateTests } from './cases/translate/index.js';

/**
 * 테스트 시스템을 초기화합니다.
 * @returns 초기화된 TestRunner 인스턴스
 */
export function initializeTestSystem(): TestRunner {
  // 테스트 러너 생성
  const testRunner = new TestRunner();

  // 테스트 카테고리 및 케이스 등록
  testRunner.registerTestCategory('fileSystem', '파일 시스템 도구 테스트', fileSystemTests);
  testRunner.registerTestCategory('terminal', '터미널 명령어 도구 테스트', terminalTests);
  testRunner.registerTestCategory('context', '컨텍스트 도구 테스트', contextTests);
  testRunner.registerTestCategory('translate', '번역 도구 테스트', translateTests);

  return testRunner;
}

// 모듈 내보내기
export { TestRunner } from './runner.js';
export { TestReporter } from './reporter.js';
export type { TestResult, TestFunction, TestSuite, TestCategory } from './runner.js';