// filepath: /Users/uhd/Documents/Projects/1.PERSONAL/03.Projects/codebot/src/utils/constants.ts
/**
 * 애플리케이션 전반에서 사용되는 상수들
 * Constants used throughout the application
 *
 * Generated by Copilot
 */

/**
 * Logger 관련 기본 상수
 * Default constants for Logger
 */
export const LOGGER_DEFAULTS = {
  /**
   * 기본적으로 항상 표시할 노드 목록
   * Default list of nodes to always show
   */
  ALWAYS_VISIBLE_NODES: [
    'translateInput',
    'analyzeTask',
    'executeStep',
    'generateResponse',
    'planExecution',
    'verifyResult'
  ]
};