import { Tool } from '../types/index.js';

/**
 * 도구 레지스트리 클래스
 * 모든 도구를 등록하고 관리하는 클래스입니다.
 */
export class ToolRegistry {
  private tools: Map<string, Tool>;

  constructor() {
    this.tools = new Map<string, Tool>();
  }

  /**
   * 도구를 등록합니다.
   * @param tool 등록할 도구
   */
  registerTool(tool: Tool): void {
    this.tools.set(tool.name, tool);
  }

  /**
   * 도구를 실행합니다.
   * @param name 실행할 도구의 이름
   * @param input 도구에 전달할 입력 데이터
   * @returns 도구 실행 결과
   */
  async executeTool(name: string, input: any): Promise<any> {
    const tool = this.tools.get(name);
    if (!tool) {
      throw new Error(`도구를 찾을 수 없습니다: ${name}`);
    }

    try {
      // 입력 데이터 검증
      tool.schema.parse(input);
      return await tool.execute(input);
    } catch (error: any) {
      // 검증 또는 실행 오류 처리
      throw new Error(`도구 실행 오류 ${name}: ${error.message}`);
    }
  }

  /**
   * 등록된 모든 도구를 반환합니다.
   * @returns 등록된 모든 도구 배열
   */
  getTools(): Tool[] {
    return Array.from(this.tools.values());
  }

  /**
   * 특정 도구를 이름으로 가져옵니다.
   * @param name 가져올 도구의 이름
   * @returns 도구 또는 undefined
   */
  getTool(name: string): Tool | undefined {
    return this.tools.get(name);
  }
}

/**
 * 도구 레지스트리
 * Tool Registry
 *
 * 모든 도구를 중앙에서 관리하는 레지스트리입니다.
 * A central registry to manage all tools.
 *
 * Generated by Copilot
 */

import { BaseTool } from './base.js';
import { ListFilesTool } from './fileSystem/listFiles.js';
import { ReadFileTool } from './fileSystem/readFile.js';
import { WriteFileTool } from './fileSystem/writeFile.js';
import { RunCommandTool } from './terminal/runCommand.js';
import { GetContextTool } from './context/getContext.js';
import { AddToContextTool } from './context/addToContext.js';
import { TranslateTool } from './translate/translate.js';

/**
 * 시스템에서 사용 가능한 모든 도구 목록을 반환합니다.
 * Returns a list of all tools available in the system.
 *
 * @returns 도구 목록 / List of tools
 */
export function getAllTools(): BaseTool[] {
  // 파일 시스템 도구
  const listFilesTool = new ListFilesTool();
  const readFileTool = new ReadFileTool();
  const writeFileTool = new WriteFileTool();

  // 터미널 도구
  const runCommandTool = new RunCommandTool();

  // 컨텍스트 도구
  const getContextTool = new GetContextTool();
  const addToContextTool = new AddToContextTool();

  // 번역 도구
  const translateTool = new TranslateTool();

  // 모든 도구 반환
  return [
    listFilesTool,
    readFileTool,
    writeFileTool,
    runCommandTool,
    getContextTool,
    addToContextTool,
    translateTool
  ];
}